# Generated by Django 5.2.1 on 2025-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
