# Generated by Django 5.2.1 on 2025-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatendimento',
            name='dia_semana',
            field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], max_length=1),
        ),
    ]
