# Generated by Django 5.2.1 on 2025-05-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_alter_horarioatendimento_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_espera', 'Em espera'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendente', max_length=10),
        ),
    ]
